DROP TABLE IF EXISTS Askareenluokka CASCADE;
DROP TABLE IF EXISTS Luokka CASCADE;
DROP TABLE IF EXISTS Askare CASCADE;
DROP TABLE IF EXISTS Tarkeysaste CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
